### ISSUE TITLE
Allow to upload a picture of the printed shape in the project page

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/beetleCloud#24]
For now, just allow to add a URL to a picture hosted somewhere else.

**Comment by bromagosa** [comment]
http://api.imgur.com/endpoints/image

**Comment by ericrosenbaum** [comment]
one idea for how the image could show up, as an inset on the thumbnail:

<img width="671" alt="screen shot 2016-08-10 at 10 19 13 am" src="https://cloud.githubusercontent.com/assets/567844/17557893/e4153670-5ee6-11e6-9eb1-7010cfdf0a29.png">

**Comment by bromagosa** [comment]
Crop uploaded image to the center of the longer dimension.
