### ISSUE TITLE
change home button

### ISSUE THREAD

**Issue by ericrosenbaum** [bromagosa/beetleCloud#50]
replace home logo with red and white bb logo, and move to left side, left aligned with page content

**Comment by bromagosa** [comment]
I need help here, this looks awful:

![image](https://cloud.githubusercontent.com/assets/1016697/17621716/95691b76-6095-11e6-954c-dbf9cc5793bf.png)

I've tried every possible combination of colors, stroke widths and visible parts I could think of, but they all look terrible... @gitduks, @ShuraChechel, can you help me out here?
