### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/beetleCloud#59]
I confess I know virtually nothing about Lua, but it seems like a cool language.

Has anyone other than Bernat gotten this up and running locally?

@bromagosa would you mind if (assuming I get this working) created a setup script and docs for running on a Mac?

**Comment by bromagosa** [comment]
You only need to know three things about Lua:

a) Everything is a pointer
b) The only data structure is the dictionary
c) All functions are anonymous and first class, "named" functions are just syntax sugar for functions being assigned to a variable.

Setting up the Beetle Cloud is super simple. I use Debian though, I really don't know how different this is going to be in MacOSX. Let me put together a short install guide, I'll try to do it before it's work time at the other side of the Pond.

**Comment by bromagosa** [comment]
Please let me know if it worked, I've written it by scavenging commands out of my work notebook: https://github.com/bromagosa/beetleCloud/blob/master/INSTALL.md

**Comment by cycomachead** [comment]
Thanks! That's super helpful!

I'll try on macOS later today and then update the doc with notes. :)

**Comment by cycomachead** [comment]
I'm getting it working, I think!

The main problem for me is that `lapis` needs Lua 5.1, it seems and that's not the default. Then there's some OpenSSL stuff on the Mac that's tricky to deal with - but I can probably make a simple install script.

**Comment by bromagosa** [comment]
Oh yeah, it runs on Lua 5.1, I forgot to mention that :)

**Comment by cycomachead** [comment]
I got everything working! At least on one computer. :)

OpenResty is a still a manual install, but it wasn't too bad. I'm going to test the script I work and then submit a PR.

**Comment by bromagosa** [comment]
Cool! Thank you! If you need more help let me know!

Oh, and when you get it up and running, let's talk about what we need to modify for it to be usable for Snap!.

**Comment by bromagosa** [comment]
@cycomachead apparently the `cloud.sql` dump was quite old. I've updated it to match the current schema. If you're in a test environment, just drop everything in the DB and rebuild the schema with this file.

**Comment by cycomachead** [comment]
Thanks!

Actually this reminds me: Did you consider storing the project XML outside of the database and using something like S3 or just the file system?

**Comment by bromagosa** [comment]
Yes, I had a talk with John at Scratch@MIT about the BeetleCloud and he explained to me that the Scratch site is following exactly the approach you suggest. Projects are stored in the FS and the rest is stored in a DB.

I can definitely see the benefit of this. Let me think about it... it'd just be a matter of replicating the `user name/project name` structure in the FS, probably hashing both user names and project names.

It's quite a lot of work, though I guess it's best to do it before we get too many users... :sweat_smile:

Anyways, we could always dump project files from the DB to the file system if this becomes a problem in the future, right?

**Comment by cycomachead** [comment]
Yeah, I was just curious. I was strongly looking at S3 when I was working on a SnapCloud a couple years ago. In that case we just stored the project ID / URL in the DB in place of the project text.

But yeah, you should always be able to migrate later. :)
