### ISSUE TITLE
"show all" link shows up in wrong place

### ISSUE THREAD

**Issue by ericrosenbaum** [bromagosa/beetleCloud#67]
in my opinion the "show all" link should be right-justified in the gray bar. this particular screenshot shows that on a user page it shows up below the bar.

<img width="420" alt="screen shot 2016-09-13 at 10 15 10 am" src="https://cloud.githubusercontent.com/assets/567844/18477277/10d30a24-799b-11e6-8203-31c3b08d13b9.png">

**Comment by bromagosa** [comment]
Uhm... which is how it shows up in my browser:

![image](https://cloud.githubusercontent.com/assets/1016697/18477379/c3bc4e98-79cd-11e6-952c-01c12b80b5ad.png)

I hate browsers :(

**Comment by ericrosenbaum** [comment]
actually it looks fine now! looks like I was just seeing an old version.

**Comment by bromagosa** [comment]
oooh right, that may have been your cache not having loaded the latest css.

(I'm in the middle of fixing a couple of minor things, like the project page that's all messed up)
