### ISSUE TITLE
Profile Error

### ISSUE THREAD

**Issue by megabyte16** [bromagosa/beetleCloud#76]
Hello, 

I am utilizing Beetle Blocks with my high school students. They created accounts yesterday and one of my students is currently experiencing an error when anyone visits her profile page. 

![screen shot 2017-04-05 at 9 43 53 am](https://cloud.githubusercontent.com/assets/26933115/24717051/f453629a-19e5-11e7-9beb-6ad1009870dc.png)

**Comment by bromagosa** [comment]
Funny! She actually added a space at the end of her username, so her proper user name is `jennarubinstein[space]`.

Of course, the browser will trim that space out of the URL, so you can access the page by either going to:

http://beetleblocks.com/users/jennarubinstein%20

or

[http://beetleblocks.com/users/jennarubinstein /](http://beetleblocks.com/users/jennarubinstein%20/)

**Comment by megabyte16** [comment]
Wow! Thank you! I had a feeling it was going to be some sort of user error when she created her account but couldn't put my finger on it.....

Thank you for your quick reply! Loving Beetle Blocks!

**Comment by bromagosa** [comment]
Actually, the error message could be a bit less cryptic... I really need to work on it! :)
