### ISSUE TITLE
Hyperblocks

### ISSUE THREAD

**Issue by nileshtrivedi** [bromagosa/beetleCloud#84]
Snap supports vector operations called hyperblocks. For example, Newton's equations of motion can be simulated with:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/19304/227254017-85b533d7-57fe-40fd-a814-7e186d59a57c.png">

But in BeetleBlocks, multiplying a list with a number does not work. So, I have to resort to this:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/19304/227254290-68cf02c0-78bf-469a-8ba0-d8e5226cd7d1.png">

What I would like to be able to do is this:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/19304/227254837-589e159c-31a2-4ee7-9f3a-91fd227d4214.png">

**Comment by bromagosa** [comment]
Yep, sorry about that. Beetle Blocks is anchored in the past (based on Snap! v5), and will remain there for the foreseeable future.

**However**! We are working on a reimagined idea based on Beetle Blocks that will be an official part of Snap! and, thus, will always be in sync with all the new features. Stay tuned for a probable beta this summer! :)

**Comment by nileshtrivedi** [comment]
@bromagosa Was there an updated on beetleblocks reimagined in 2023?

**Comment by bromagosa** [comment]
Yes! It's all going according to plan and we should release a beta version somewhat soonish :)
