### ISSUE TITLE
We can't login into Beetle blocks accounts

### ISSUE THREAD

**Issue by nzuniga1** [bromagosa/beetleCloud#85]
Error
/usr/local/share/lua/5.1/lapis/db/postgres.lua:56: connection refused
Traceback
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/lapis/db/postgres.lua:56: in function 'select'
	/usr/local/share/lua/5.1/lapis/db/base_model.lua:557: in function 'find'
	./api.lua:217: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf.compiled:33):2: in function <content_by_lua(nginx.conf.compiled:33):1>

**Comment by bromagosa** [comment]
Sorry about that. Beetle Blocks hasn't been in active development for a while, and we hadn't noticed that the cloud was down. It's up again now.
